### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Helmeboi** [andripwn/Apple-Validator#1]
This is what I get

> PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /root/Apple-Validator/Apple-Validator/app.php on line 49
> PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in /root/Apple-Validator/Apple-Validator/app.php on line 49
> PHP Notice:  Use of undefined constant CURLOPT_MAXREDIRS - assumed 'CURLOPT_MAXREDIRS' in /root/Apple-Validator/Apple-Validator/app.php on line 49
> PHP Notice:  Use of undefined constant CURLOPT_CONNECTTIMEOUT - assumed 'CURLOPT_CONNECTTIMEOUT' in /root/Apple-Validator/Apple-Validator/app.php on line 49
> PHP Notice:  Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in /root/Apple-Validator/Apple-Validator/app.php on line 49
> PHP Notice:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_COOKIESESSION - assumed 'CURLOPT_COOKIESESSION' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_COOKIEJAR - assumed 'CURLOPT_COOKIEJAR' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_COOKIEFILE - assumed 'CURLOPT_COOKIEFILE' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_COOKIESESSION - assumed 'CURLOPT_COOKIESESSION' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_COOKIEJAR - assumed 'CURLOPT_COOKIEJAR' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_COOKIEFILE - assumed 'CURLOPT_COOKIEFILE' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' in /root/Apple-Validator/Apple-Validator/app.php on line 59
> PHP Fatal error:  Uncaught Error: Call to undefined function RollingCurl\curl_multi_init() in /root/Apple-Validator/Apple-Validator/RollingCurl/RollingCurl.php:212
> Stack trace:
> #0 /root/Apple-Validator/Apple-Validator/app.php(96): RollingCurl\RollingCurl->execute()
> #1 {main}
>   thrown in /root/Apple-Validator/Apple-Validator/RollingCurl/RollingCurl.php on line 212
>

**Comment by andripwn** [comment]
**Hi!** @Helmeboi ,lets make step by step installation

```
install the php 
gitclone https://github.com/andripwn/Apple-Validator.git
cd Apple-Validator.git
chmod +x app.php
php app.php
```

**Comment by Helmeboi** [comment]
Done all that, still getting the exact same error.
PS: is the python version updated?

**Comment by andripwn** [comment]
you noob for using it , check the step by step
:)

**Comment by Helmeboi** [comment]
your shit is bad chink admit it!
